#!/usr/bin/env node
/**
 * @license
 * Copyright 2022-2026 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

// Validates that the published .d.ts artifacts of @matter/* packages compile cleanly under strict
// TypeScript without skipLibCheck and without dev-only resolution conditions.  Catches issues that
// matter.js's internal build hides via skipLibCheck=true and customConditions=["dev-types"], but
// which downstream consumers using strict TS will hit.
//
// Run via: `npm run validate-dts`

import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), "..", "..");

// Core packages whose .d.ts is generated by matter.js codegen.  Platform/runtime adapter packages
// (nodejs-ble, nodejs-ws, mqtt, react-native, cli-tool) are excluded because their .d.ts surfaces
// reflect transitive dependency type quality (react-native, memlab, etc.) which is outside our
// control.
const PACKAGES = [
    "@matter/general",
    "@matter/model",
    "@matter/types",
    "@matter/protocol",
    "@matter/node",
    "@matter/main",
    "@matter/testing",
    "@matter/nodejs",
    "@project-chip/matter.js",
];

// An error is attributed to matter.js if its file path is inside one of these prefixes (matched
// against the absolute path printed by tsc).  Errors in TypeScript's bundled lib or in transitive
// dependencies are ignored because they're not produced by our codegen.
const MATTER_PATH_FRAGMENTS = ["/@matter/", "/@project-chip/matter.js/"];

function tscPath() {
    return resolve(REPO_ROOT, "node_modules", "typescript", "bin", "tsc");
}

function isMatterError(line) {
    return MATTER_PATH_FRAGMENTS.some(frag => line.includes(frag));
}

function main() {
    const tmp = mkdtempSync(join(tmpdir(), "matter-dts-check-"));
    try {
        const importStatements = PACKAGES.map(p => `import ${JSON.stringify(p)};`).join("\n");
        writeFileSync(join(tmp, "repro.ts"), `${importStatements}\n`);

        const tsconfig = {
            compilerOptions: {
                target: "esnext",
                module: "esnext",
                moduleResolution: "bundler",
                strict: true,
                noEmit: true,
                skipLibCheck: false,
            },
            include: ["repro.ts"],
        };
        writeFileSync(join(tmp, "tsconfig.json"), JSON.stringify(tsconfig, null, 4));

        // Symlink node_modules from the repo so imports resolve against built dist.
        spawnSync("ln", ["-s", join(REPO_ROOT, "node_modules"), join(tmp, "node_modules")], {
            stdio: "inherit",
        });

        const result = spawnSync(process.execPath, [tscPath(), "-p", "."], {
            cwd: tmp,
            encoding: "utf8",
        });

        const output = `${result.stdout || ""}${result.stderr || ""}`;
        const errorLines = output.split("\n").filter(l => l.includes("error TS"));
        const matterErrors = errorLines.filter(isMatterError);

        if (matterErrors.length === 0) {
            console.log(
                `✓ All ${PACKAGES.length} packages produce clean .d.ts ` +
                    `(${errorLines.length - matterErrors.length} non-matter errors ignored)`,
            );
            process.exit(0);
        }

        console.error(`✗ ${matterErrors.length} matter.js .d.ts error(s):\n`);
        for (const err of matterErrors) {
            console.error(err);
        }
        console.error(`\n${errorLines.length - matterErrors.length} non-matter errors ignored.`);
        process.exit(1);
    } finally {
        rmSync(tmp, { recursive: true, force: true });
    }
}

main();
