/**
 * @license
 * Copyright 2022-2026 Matter.js Authors
 * SPDX-License-Identifier: Apache-2.0
 */

import { InternalError, Logger } from "#general";
import { RequirementElement } from "#model";
import { EndpointFile } from "./EndpointFile.js";

const logger = Logger.get("requirement-coverage");

/**
 * Set when a requirement the specification states reaches no generated artifact.
 *
 * Logging alone is what let eighty-seven requirements go missing for a release: the log line was there every build
 * and nobody read it. The run's exit status is the part a script can act on.
 */
export let requirementsLost = false;

export function reportRequirementLost(message: string) {
    logger.error(message);
    requirementsLost = true;
}

/**
 * Requirement kinds that describe a cluster on this endpoint, generated by {@link RequirementGenerator}.
 */
const CLUSTER_KINDS = new Set<string>([
    RequirementElement.ElementType.ServerCluster,
    RequirementElement.ElementType.ClientCluster,
]);

/**
 * Requirement kinds an endpoint deliberately does not carry.
 *
 * These describe another device type this one composes, or a condition its requirements are stated against.
 * `DeviceTypeModel.requirements` states them losslessly, so generating a second copy here would mean maintaining the
 * same facts in two places and inventing keys for the instances the model distinguishes structurally.
 */
const MODEL_ONLY_KINDS = new Set<string>([
    RequirementElement.ElementType.DeviceType,
    RequirementElement.ElementType.Condition,
]);

/**
 * Fail on a requirement kind nothing accounts for.
 *
 * A silent drop is what let eighty-seven requirements go missing for a whole release, so a new member of
 * {@link RequirementElement.ElementType} stops the build until it is either generated or listed as model-only.
 */
export function assertAllKindsHandled(file: EndpointFile) {
    for (const requirement of file.model.requirements) {
        const { element } = requirement;
        if (CLUSTER_KINDS.has(element) || MODEL_ONLY_KINDS.has(element)) {
            continue;
        }

        throw new InternalError(
            `${file.model.name} states a ${element} requirement (${requirement.name}) that no generator claims`,
        );
    }
}
